version: '3.8'
services:

  hello-go:
    image: golang:1.20-alpine
    command: ["go", "test", "-v", "./mysqlhd", "-count", "1"]
    working_dir: /app
    # networks:
      # default:
        # aliases:
          # - hello.go.lab.local
    environment:
      TZ: 'Asia/Shanghai'
    volumes:
      - ./:/app
      - ~/Work/workspace/go:/go

networks:
  default:
    name: lab
